version: '3'
services:
  backend:
    build: .
    container_name: wasteno-backend
    volumes:
      - ./src:/src
      - ./.env:/src/.env
      - ./test:/test
      - ./scripts:/scripts
      - ${FRONTEND_PATH}:/public
    ports: 
      - 3000:${PORT}
    links:
      - db
      - testdb
    depends_on:
      - db
      - testdb
  db:
    image: postgres
    restart: always
    container_name: wasteno-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/db
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db-data:/data
  testdb:
    image: postgres
    restart: always
    container_name: wasteno-testdb
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/db
      - POSTGRES_DB=${DB_NAME}
