version: '3'
services:
  backend:
    build: .
    container_name: wasteno-backend
    volumes:
      - ./src:/src
      - ./.env:/src/.env
      - ${FRONTEND_PATH}:/public
    ports: 
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3
    container_name: wasteno-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - ./db-data:/data
    ports:
      - 27017:27017
    command: --smallfiles
