version: '3'
services:
  backend:
    build: .
    container_name: wasteno-backend
    volumes:
      - ./src:/src
      - ./.env:/src/.env
      - ${FRONTEND_PATH}:/public
    ports: 
      - 3000:${PORT}
    links:
      - pgdb
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    restart: always
    container_name: wasteno-mongodb
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/db
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db-data:/data
