module.exports = {
  bad_json: 'bad json',
  common_auth_expired: 'login expired',
  common_name_missing: 'name missing',
  common_name_length_short: 'name too short',
  common_name_length_long: 'name too long',
  common_name_out_of_charset: 'name contains characters not in the allowed charset',
  common_username_missing: 'username missing',
  common_username_exists: 'username already exists',
  common_username_length_short: 'username too short',
  common_username_length_long: 'username too long',
  common_username_out_of_charset: 'username contains characters not in the allowed charset',
  common_password_missing: 'password missing',
  common_password_length_short: 'password too short',
  common_password_length_long: 'password too long',
  common_password_out_of_charset: 'password contains characters not in the allowed charset',
  common_email_missing: 'email missing',
  common_email_invalid: 'email not valid',
  common_phone_missing: 'phone missing',
  common_phone_invalid: 'phone not valid',
  common_object_missing: 'object is missing',
  common_object_username_missing: 'object username missing',
  common_object_username_length_short: 'object username too short',
  common_object_username_length_long: 'object username too long',
  common_object_username_out_of_charset: 'object username contains characters not in the allowed charset',
  common_login_no: 'not logged in',
  common_login_yes: 'already logged in',
  common_login_invalid: 'password or username not valid',
  common_login_before_ban_end: 'tried to log in unsuccesfully too many times',
  common_login_unexpected: 'your credentials might have changed',
  common_lon_invalid: 'longitude is invalid',
  common_lat_invalid: 'latitude is invalid',
  common_address_missing: 'address missing',
  common_address_invalid: 'address is invalid',

  sale_description_length_short: 'description too short',
  sale_description_length_long: 'description too long',
  sale_description_out_of_charset: 'description contains characters not in the allowed charset',

  receiver_not_exists: 'receiver doesn\'t exist',
  provider_not_exists: 'provider doesn\'t exist',
  sale_name_exists: 'sale name alraedy exists',
};
