const errors = {
  bad_json: 'bad json',
  common_auth_expired: 'login expired',
  common_name_missing: 'name missing',
  common_name_length_short: 'name too short',
  common_name_length_long: 'name too long',
  common_name_out_of_charset: 'name contains characters not in the allowed charset',
  common_username_missing: 'username missing',
  common_username_exists: 'username already exists',
  common_username_length_short: 'username too short',
  common_username_length_long: 'username too long',
  common_username_out_of_charset: 'username contains characters not in the allowed charset',
  common_password_missing: 'password missing',
  common_password_length_short: 'password too short',
  common_password_length_long: 'password too long',
  common_password_out_of_charset: 'password contains characters not in the allowed charset',
  common_email_missing: 'email missing',
  common_email_invalid: 'email not valid',
  common_email_length_long: 'email too long',
  common_phone_missing: 'phone missing',
  common_phone_invalid: 'phone not valid',
  common_object_missing: 'main param is missing',
  common_object_not_array: 'main param is not an array',
  common_object_username_missing: 'main param username missing',
  common_object_username_length_short: 'main param username too short',
  common_object_username_length_long: 'main param username too long',
  common_object_username_out_of_charset: 'main param username contains characters not in the allowed charset',
  common_login_no: 'not logged in',
  common_login_yes: 'already logged in',
  common_login_invalid: 'password or username not valid',
  common_login_before_ban_end: 'tried to log in unsuccesfully too many times',
  common_login_unexpected: 'your credentials might have changed',
  common_not_verified: 'your user was not verified',
  common_lon_invalid: 'longitude is invalid',
  common_lat_invalid: 'latitude is invalid',
  common_address_missing: 'address missing',
  common_address_invalid: 'address is invalid',
  common_address_out_of_charset: 'address is out of charset',
  common_address_length_short: 'address is too short',
  common_address_length_long: 'address is too long',
  common_location_multiple_main: 'main location set multiple times',
  common_location_name_exists: 'location name already exists',
  common_eid_missing: 'eid missing',
  common_eid_length_short: 'eid too short',
  common_eid_length_long: 'eid too long',
  common_eid_out_of_charset: 'eid contains characters not in the allowed charset',
  common_eid_portion_missing: 'eid portion missing',
  common_eid_portion_length_short: 'eid portion too short',
  common_eid_portion_length_long: 'eid portion too long',
  common_eid_portion_out_of_charset: 'eid portion contains characters not in the allowed charset',
  common_offset_invalid: 'offset is invalid',
  common_amount_invalid: 'amount is invalid',
  common_amount_size_big: 'amount is too big',
  common_amount_size_zero: 'amount cannot be zero',

  sale_description_missing: 'description missing',
  sale_description_length_short: 'description too short',
  sale_description_length_long: 'description too long',
  sale_description_out_of_charset: 'description contains characters not in the allowed charset',

  receiver_not_exists: 'receiver doesn\'t exist',
  receiver_too_many_orders: 'receiver has too many orders',
  provider_not_exists: 'provider doesn\'t exist',
  provider_eid_not_matching: 'provider eid does not match',
  order_eid_not_exists: 'order eid doesn\'t exist',
  order_eid_not_matching_receiver: 'order eid doesn\'t match receiver',
  location_eid_not_exists: 'location eid doesn\'t exist',
  sale_eid_exists: 'sale eid already exists',
  sale_eid_not_exists: 'sale eid doesn\'t exist',
  sale_eid_missing: 'sale eid missing',
  sale_instance_quantity_invalid: 'sale instance quantity is invalid',
  sale_instance_expiry_missing: 'sale instance expiry missing',
  sale_instance_expiry_passed: 'sale instance has already exipired',
  sale_instance_expiry_invalid: 'sale instance expiry is invalid',
  sale_instance_eid_exists: 'sale instance eid already exists',
  sale_instance_eid_not_exists: 'sale instance eid doesn\'t exist',
  sale_instance_eid_missing: 'sale instance eid missing',
  sale_instance_parent_eid_not_exists: 'sale instance parent eid doesn\'t exist',
  sale_instance_location_name_missing: 'sale instance location name missing',
  sale_instance_location_name_invalid: 'sale instance location index is invalid',
  sale_instance_location_name_length_short: 'sale instance location index is too short',
  sale_instance_location_name_length_long: 'sale instance location index is too long',
  sale_instance_location_name_out_of_charset: 'sale instance location index is out of charset',
  sale_search_term_missing: 'sale search term missing',
  sale_search_term_length_long: 'sale search term is too long',
  sale_search_term_length_short: 'sale search term is too short',
  sale_search_term_out_of_charset: 'sale search term is out of charset',

  unexpected: 'unexpected error. Contact owners',
};

module.exports = new Proxy(errors, {
  get(obj, accessor) {
    if (obj.hasOwnProperty(accessor)) {
      return obj[accessor];
    }
    console.error(`UNACCOUNTED ERROR ACCESSOR: ${accessor}`);
    return accessor;
  },
});
